sudo: required
services:
  - docker

before_install:
  - docker build -t mgviero/docker-vue -f Dockerfile.dev .

script:
  - docker run mgviero/docker-vue yarn lint 

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: docker
  env: Docker-env
  bucket_name: elasticbeanstalk-sa-east-1-614365341039
  bucket_path: docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
